openapi: 3.0.3
info:
  title: Motion MCP Server Tools
  description: MCP tool definitions for Motion task management integration
  version: 1.0.0

servers:
  - url: mcp://motion/v1
    description: Model Context Protocol server

components:
  schemas:
    MCPToolResponse:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            type: object
            properties:
              text_type:
                type: string
                enum: [text]
              text_content:
                type: string
        isError:
          type: boolean
          default: false

    Priority:
      type: string
      enum: [LOW, MEDIUM, HIGH, URGENT]

    ListProjectsRequest:
      type: object
      properties:
        workspaceId:
          type: string
        limit:
          type: integer
          minimum: 1
          maximum: 100
          default: 50
        cursor:
          type: string

    CreateTaskRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
        priority:
          $ref: '#/components/schemas/Priority'
        enrich:
          type: boolean
          default: false

paths:
  /tools/motion.project.list:
    post:
      summary: List all projects with pagination
      operationId: listProjects
      x-mcp-tool:
        controller: ProjectController
        action: list
        validation:
          required: []
          optional: [workspaceId, limit, cursor]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListProjectsRequest'
      responses:
        '200':
          description: Projects listed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MCPToolResponse'

  /tools/motion.task.create:
    post:
      summary: Create a new task
      operationId: createTask
      x-mcp-tool:
        controller: TaskController
        action: create
        validation:
          required: [name]
          optional: [description, priority, enrich]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MCPToolResponse'